services:
  - postgres:latest

variables:
  POSTGRES_DB: project_krama

stages:
  - build
  - staging
  - production

build-code:
  stage: build
  variables:
    DATABASE_URL: "postgresql://postgres@postgres:5432/$POSTGRES_DB"
  script:
    - apt-get update && apt install -y -qq nodejs
    - gem install bundler --no-ri --no-rdoc
    - gem install execjs
    - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
    - bundle exec rake db:migrate
    - bundle exec rake db:seed
  except:
    - master
    - develop

deploy-staging:
  stage: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$STAGING_APP --api-key=$HEROKU_API_KEY
    - curl --data chat_id=$TELEGRAM_CHAT_ID --data-urlencode text="[Prod-Krama-BOT] Deploy Done! | Deployed by $GITLAB_USER_NAME | Update in $GITLAB_FEATURES | $CI_COMMIT_TITLE" $TELEGRAM_BOT_URL
    - develop

deploy-production:
  stage: production
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$PROD_APP --api-key=$HEROKU_API_KEY
    - curl --data chat_id=$TELEGRAM_CHAT_ID --data-urlencode text="[Prod-Krama-BOT] Deploy Done! | Deployed by $GITLAB_USER_NAME | Update in $GITLAB_FEATURES | $CI_COMMIT_TITLE" $TELEGRAM_BOT_URL
  only:
    - master
