Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Max: 150
